import type { Project } from "./types";

export const initialProjects: Project[] = [
  {
    id: 1,
    title: "Harvest Frenzy",
    description: "Мини-игра в Харвест по Path of Exile.",
    category: "PoE",
    date: "2025-08-12",
    icon: "/icons/harvest.png",
    link: "https://klon008.github.io/harvest_frenzy",
  },
  {
    id: 2,
    title: "Exile Heist Trades",
    description: "Приложение для быстрого поиска предметов связанных с Heist в PoE, а так же анализа цен.",
    category: "PoE",
    date: "2025-08-12",
    icon: "/icons/HeistAmulet.webp",
    link: "https://exile-heist-trades.vercel.app",
  },
  {
    id: 3,
    title: "Betrayal Cheat Sheet",
    description: "Таблица для PoE с наградами Syndicate. Позволяет изменять таблицу и экспортировать в jpg",
    category: "PoE",
    date: "2025-08-12",
    icon: "/icons/syndicate.png",
    link: "https://klon008.github.io/Path-of-Exile---Betrayal-Cheat-Sheet-3.26",
  },
  {
    id: 4,
    title: "PoE Divine Converter",
    description: "Небольшой проект для быстрой конвертации валют PoE и подсчета их стэше.",
    category: "PoE",
    date: "2022-05-20",
    icon: "/icons/Divine_Orb_inventory_icon.png",
    link: "https://klon008.github.io/poe-helper",
  },
  {
    id: 5,
    title: "Yandex Metric Dashboard",
    description: "Дашборд по всем метрикам на аккаунте. полезно для анализа, если у вас много сайтов.",
    category: "Веб-приложение",
    date: "2025-08-12",
    icon: "/icons/y_metric.png",
    link: "http://crmtyx7kw2.temp.swtest.ru/metrika_dashboard/index.html",
  },
  {
    id: 6,
    title: "diablo2fresher",
    description: "База предметов и быстрый поиск по ним в diablo 2.",
    category: "d2",
    date: "2020-06-18",
    icon: "/icons/didi.png",
    link: "https://klon008.github.io/diablo2fresher/",
  },
    {
    id: 7,
    title: "Дек Мастер",
    description: "Лендинг для компании производящей Террасные доски",
    category: "Landing",
    date: "2024-01-10",
    icon: "/icons/tl.webp",
    link: "https://klon008.github.io/dek_master/",
  },
  {
    id: 8,
    title: "bakery_website",
    description: "Верстка довольно знаменитого шаблона",
    category: "Landing",
    date: "2023-12-01",
    icon: "/icons/bread.png",
    link: "https://klon008.github.io/bakery_website",
  },
  {
    id: 9,
    title: "Vikings: War of Clans",
    description: "Проект по продажи услуг в мобильной игре. А также клановое взаимодействие.",
    category: "Веб-приложение",
    date: "2019-08-06",
    icon: "/icons/vwoc.png",
    link: "https://klon008.github.io/vikings",
  },
  {
    id: 10,
    title: "Leagueofinternity",
    description: "Форум-Портал для гильдии в игре World of Warcraft",
    category: "Веб-приложение",
    date: "2017-09-28",
    icon: "/icons/WoW_Logo.png",
    link: "https://klon008.github.io/leagueofinternity/",
  },
  {
    id: 11,
    title: "Process simulation",
    description: "Симулятор управления процессами в Операционной Системе",
    category: "Веб-приложение",
    date: "2019-02-18",
    icon: "/icons/tl.webp",
    link: "https://klon008.github.io/process",
  },
  {
    id: 12,
    title: "Quantum llc",
    description: "Сайт компании по IT разработке",
    category: "Landing",
    date: "2023-08-08",
    icon: "/icons/Quantum.png",
    link: "https://www.quantumllc.ru",
  },
];
